### ISSUE TITLE
Review #1 - El viewport se rompe al cambiar la resolución

### ISSUE THREAD

**Issue by FacundoEG** [cynthiadaubert/Desafio_Modulo_4#1]
Hola Cynthia ! como estas? te cuento que estuve revisando un poco tu page y me encanto el diseño! pero encontre algunos problemas en el comportamiento visual que me gustaría mostrarte:

En la home page, fijate que muchos de los elementos no responden bien al cambio de resolución y se salen del viewport, acordate como vimos en el desafío del modulo 3, tendrían que ir adaptandose a las diferentes resoluciones para que no se pierdan:
![Screenshot_20220216_102610](https://user-images.githubusercontent.com/79592789/154273980-4987c0d9-f626-40cc-9835-8c6e027cbf49.png)
![Screenshot_20220216_102701](https://user-images.githubusercontent.com/79592789/154274088-f41644f8-7ec7-4d1e-94d3-105175dc8647.png)
Te recomiendo que si estas usando flex, te bases mas en las propiedades que tiene para separar (como "gap") y no tanto en dejar margenes fijos porque pierde responsividad.

Luego noto lo mismo en las demas paginas:
![Screenshot_20220216_102928](https://user-images.githubusercontent.com/79592789/154274519-c3b37160-da98-40bc-94aa-ec365c0e6c79.png)

Sacando esos detalles, el desafío esta muy bien! el diseño destaca bocha y se puede navegar tranquilamente!

Así que de mi parte te pediría que revises ese tema de la responsividad y vuelvas a mandar el desafío, ya que es una de las premisas que la pagina no se rompa al cambiar de resolución.

Cualquier duda estoy para ayudarte y no olvides que también podes consultar en el canal de la carrera! 

Saludos!

**Comment by cynthiadaubert** [comment]
@FacundoEG Hola! que bueno que haya gustado! 
Y si, me olvidé de tener en cuenta la responsividad y usé todo grid sin pensar. Ahora cambié todo a flex porque por lo que ví quedaba mejor de esa forma. Revisé todos los contenedores y modifiqué el max-width de varios sino se salian todos del margen y ahora creo que se ve mejor.

Gracias!!

**Comment by FacundoEG** [comment]
Hola Cynthia! volvi a revisar la page y las cards quedaron acomodadas, pero segui encontrando algunos errores de responsividad, te los voy a dejar abajo con algunas sugerencias, pero quedate tranqui que te dejo como aprobado el desafío porque la verdad noto que entendiste bien las premisas que se proponian.

1. El footer te va a quedar siempre un poco escondido porque tiene un ancho fijo de 1400px aprox, pero los contenedores padres tienen 100vw de ancho y hace que se comporte raro, te recomiendo que uses width de 100% en los contenedores y que agreges un padding asi queda mejor.
![image](https://user-images.githubusercontent.com/79592789/154608412-f1552b77-9daf-4bca-832a-58f0e541e4ae.png)
![image](https://user-images.githubusercontent.com/79592789/154609595-61ac799c-9694-4b6e-adcc-297b82a95f6c.png)

2. Como puse arriba, fijate que muchos elementos tienen width en 100vw pero despues adentro en porcentajes, te recomendarias que lo dejes todo en porcentaje asi queda mas prolijo.

3. El form con un space around y manejandole mas el width tambien queda mejor
![image](https://user-images.githubusercontent.com/79592789/154609987-cdd2979a-0295-4922-8c1f-e3c081912e7e.png)

En definitiva, con correjir un poco el width de los contenedores ya quedaría todo mejor!

Lo que si me parece muy genial como destaca el diseño y lo prolijo del codigo, asi que te felicito por eso! 

Como te digo, todo se mejora despues, asi que de mi parte te dejo mi LGTM y te deseo exitos para el proximo modulo!

Saludos!
